# DataFrame Analysis Exercise

**Import the `bestsellers.csv` dataset and use it to answer the following questions:**

* Find the lowest User Rating in the DF
* Find the highest Price in the DF
* What is the average User Rating?
* What the average User Rating of the first 5 rows?
* What User Review score appeared the most?
* What is the total (sum) of all the values in the Reviews column?
* How many different authors are featured in the dataset?
* Which author wrote the most number of books on the list?  How many did they write?

In [ ]:
import pandas as pd

bestsellers = pd.read_csv('../datasets/data/bestsellers.csv')
bestsellers.head()

In [ ]:
# 1.
bestsellers.min()
# lowest user rating is 3.3

In [ ]:
#2.
bestsellers.max()
# highest price in df is 105

In [ ]:
# 3.
bestsellers.mean(numeric_only=True)
# avg user rating is 4.618

User Rating        4.618364
Reviews        11953.281818
Price             13.100000
Year            2014.000000
dtype: float64

In [9]:
#4.
bestsellers.head().mean(numeric_only=True)
# avg user rating of first 5 rows is 4.7

User Rating        4.7
Reviews        13494.0
Price             12.6
Year            2016.2
dtype: float64

In [ ]:
#5.
bestsellers.mode(numeric_only=True)
# NaN

    User Rating  Reviews  Price  Year
0           4.8   8580.0    8.0  2009
1           NaN      NaN    NaN  2010
2           NaN      NaN    NaN  2011
3           NaN      NaN    NaN  2012
4           NaN      NaN    NaN  2013
5           NaN      NaN    NaN  2014
6           NaN      NaN    NaN  2015
7           NaN      NaN    NaN  2016
8           NaN      NaN    NaN  2017
9           NaN      NaN    NaN  2018
10          NaN      NaN    NaN  2019

In [ ]:
#6.
bestsellers.sum(numeric_only=True)
# 6574305

User Rating       2540.1
Reviews        6574305.0
Price             7205.0
Year           1107700.0
dtype: float64

In [ ]:
#7.
bestsellers.describe(include=['str'])
# 248 unique authors

,Name,Author,Genre
count,550,550,550
unique,351,248,2
top,Publication Manual of the American Psychologic...,Jeff Kinney,Non Fiction
freq,10,12,310

In [ ]:
#8.
bestsellers.describe(include=['str'])
# Jeff Kinney, 12

,Name,Author,Genre
count,550,550,550
unique,351,248,2
top,Publication Manual of the American Psychologic...,Jeff Kinney,Non Fiction
freq,10,12,310